# Generated by Django 2.2 on 2019-06-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='href',
            field=models.CharField(max_length=32),
        ),
    ]
