# Generated by Django 2.2 on 2019-06-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='pid',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
